site_name: Eungabi
site_url: https://easternkite.github.io/Eungabi
site_author: easternkite
site_description: A Compose Multiplatform Library which supports Plaform Native Features like Predictive Back Gestures in android and Swipe-to-Back Gesture in iOS.

# Repository
repo_name: easternkite/eungabi
repo_url: https://github.com/easternkite/eungabi
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2024 easternkite

nav:
  - Getting started:
      - Overview: index.md
      - Installation: getting-started/installation.md
      - Quick start: getting-started/quick_start.md
  - Navigation:
      - Navigate between composables: navigation/navigate-between-composables.md
      - Passing arguments: navigation/passing-arguments.md
  - API Docs: 'https://easternkite.github.io/eungabi/api/'
  - Sample App: 'https://easternkite.github.io/eungabi/sampleApp/'

  # Configuration
theme:
  name: 'material'

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - navigation.expand
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  favicon: media/logo/eungabi_logo.png
  logo: media/logo/eungabi_logo.png
  icon:
    logo: logo

# Plugins
plugins:
  - search

# Customization
extra:
  social:

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
