name: Check Test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check Unit Test
        run: ./gradlew :eungabi:testDebugUnitTest

      - name: Check Desktop Test
        run: ./gradlew :eungabi:desktopTest
