name: Check Test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore cached gradle
        id: cache-gradle-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-caches

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Check Unit Test
        run: ./gradlew :eungabi:testDebugUnitTest

      - name: Check Desktop Test
        run: ./gradlew :eungabi:desktopTest

      - name: Cache gradle caches
        id: cache-gradle-save
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ steps.cache-gradle-restore.outputs.cache-primary-key }}
