name: Deploy Compose Multiplatform to gh-pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Compose Multiplatform Web App
        run: |
          ./gradlew :shared:jsBrowserDistribution

      - name: Prepare for deployment
        run: |
          mkdir -p deploy/sampleApp
          cp -r shared/build/dist/js/productionExecutable/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_dir: ./deploy